// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDugd59L7iOpUmUdp3HoxnHNOmiI2rjE',
    appId: '1:881178665884:android:923887e497979682e59e59',
    messagingSenderId: '881178665884',
    projectId: 'rakwa-331713',
    databaseURL: 'https://rakwa-331713-default-rtdb.firebaseio.com',
    storageBucket: 'rakwa-331713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARcJwfHBkUl84WSlMIAGTL5dwJn-fmRnU',
    appId: '1:881178665884:ios:d4364b5b4bf95575e59e59',
    messagingSenderId: '881178665884',
    projectId: 'rakwa-331713',
    databaseURL: 'https://rakwa-331713-default-rtdb.firebaseio.com',
    storageBucket: 'rakwa-331713.appspot.com',
    iosClientId: '881178665884-hkl20o9bmolqaeg7bgescnqp12m4gh6v.apps.googleusercontent.com',
    iosBundleId: 'rakwa.turkey.com',
  );
}
